### PR TITLE
Rename security PDF to be more URL friendly

### PR DESCRIPTION
**Pull request by vampeel**
This PR renames the security overview PDF to removes spaces from the file name.

### CODE REVIEW

**Comment by jeremy** [comment]
Named this way for friendly filename once downloaded! In basecamp.com we use a /security-overview.pdf rewrite to get a friendly URL: https://github.com/basecamp/basecamp.com/blob/80f36e6b066aef2bb0a64a206c4c7fdaf326e224/config/nginx/container/rewrites.conf#L240

**Comment by vampeel** [comment]
@jeremy the name with spaces breaks the markdown parser in 11ty. I could probably try to work around the issue, but it seems like an awful lot of work for not much gain.

**Comment by jeremy** [comment]
I'd rather not regress to a techie-looking filename, or need to add another URL redirect to account for the now-missing URL on basecamp.com. I'm happy to take on that work! I'd hope it's a matter of "just" escaping spaces. Can you give me a pointer where I can reproduce the problem?

**Comment by vampeel** [comment]
IMO it's more of a trade off than a regression as spaces in URLs are ugly and not awesome (subjective opinion of course). I don't feel strongly about it though. If you restore the original file name in hey.com main, you'll see this at the bottom of the /policies/security:

Screen Shot 2021-03-12 at 2 43 11 PM

As you can see, the Markdown isn't being rendered into a link.

**Comment by vampeel** [comment]
Confirming that if you encode the space characters in the URL, it works fine.

**Pull request merged**
